# -*- coding: utf-8 -*-
"""SpeechOcean_modified.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1oZw5kjJx_HpMWaqy3PBDZKG34RdTelGQ

GOP SCORES
"""

import zipfile

with zipfile.ZipFile(r'/content/speechocean.zip', 'r') as zip_ref:
    zip_ref.extractall('/content/')

!find /content -type d | grep learners

from pathlib import Path

# Path to learners folder containing all txt files

LEARNER_DIR = "/content/speechocean/train/learners"

txt_files = sorted(Path(LEARNER_DIR).glob("*.txt"))

print("Total txt files:", len(txt_files))

def extract_words(txt_path):

    words = []
    current_word = []

    with open(txt_path, "r") as f:
        lines = f.readlines()

    for line in lines:

        line = line.strip()

        if line == "":
            continue

        parts = line.split()

        if len(parts) != 2:
            continue

        phone = parts[0]
        score = float(parts[1])

        if phone == "SIL":
            continue

        # Beginning of word
        if phone.endswith("_B"):

            if len(current_word) > 0:
                words.append(current_word)

            current_word = [score]

        # Inside word
        elif phone.endswith("_I"):

            current_word.append(score)

        # End of word
        elif phone.endswith("_E"):

            current_word.append(score)
            words.append(current_word)
            current_word = []

    if len(current_word) > 0:
        words.append(current_word)

    return words

import numpy as np
from scipy.stats import skew, kurtosis

def compute_word_features(scores):

    scores = np.array(scores, dtype=float)

    if len(scores) == 0:
        return None

    sorted_scores = np.sort(scores)

    q10 = np.percentile(scores,10)
    q25 = np.percentile(scores,25)
    q75 = np.percentile(scores,75)
    q90 = np.percentile(scores,90)

    return {

        # Existing
        "mean_gop": np.mean(scores),
        "median_gop": np.median(scores),
        "min_gop": np.min(scores),
        "max_gop": np.max(scores),
        "std_gop": np.std(scores),
        "variance_gop": np.var(scores),
        "range_gop": np.ptp(scores),

        # Counts
        "phoneme_count": len(scores),
        "negative_count": np.sum(scores < 0),
        "negative_ratio": np.mean(scores < 0),
        "below2_count": np.sum(scores < 2),
        "below4_count": np.sum(scores < 4),
        "below6_count": np.sum(scores < 6),
        "below8_count": np.sum(scores < 8),

        # Bottom / Top
        "bottom1": sorted_scores[0],
        "bottom2_avg": np.mean(sorted_scores[:min(2,len(scores))]),
        "bottom3_avg": np.mean(sorted_scores[:min(3,len(scores))]),
        "bottom_half_avg": np.mean(sorted_scores[:max(1,len(scores)//2)]),

        "top1": sorted_scores[-1],
        "top2_avg": np.mean(sorted_scores[-min(2,len(scores)):]),
        "top3_avg": np.mean(sorted_scores[-min(3,len(scores)):]),

        # Percentiles
        "p10": q10,
        "p25": q25,
        "p75": q75,
        "p90": q90,

        # Spread
        "iqr": q75-q25,
        "mean_abs_dev": np.mean(np.abs(scores-np.mean(scores))),
        "rms_gop": np.sqrt(np.mean(scores**2)),
        "coeff_var": np.std(scores)/(np.mean(scores)+1e-6),

        # Shape
        "skewness": skew(scores) if len(scores)>2 else 0,
        "kurtosis": kurtosis(scores) if len(scores)>3 else 0,

        # Good vs Bad
        "good_ratio": np.mean(scores>6),
        "excellent_ratio": np.mean(scores>8),
        "poor_ratio": np.mean(scores<4),

        # Difference
        "max_min_gap": np.max(scores)-np.min(scores),
        "top_bottom_gap": np.mean(sorted_scores[-2:])-np.mean(sorted_scores[:2]),

        # Trimmed
        "trimmed_mean": np.mean(sorted_scores[1:-1]) if len(scores)>2 else np.mean(scores)
    }

from tqdm.notebook import tqdm
import pandas as pd

#Word-Level Features
word_rows = []

for txt_file in tqdm(txt_files):

    speaker = txt_file.stem

    words = extract_words(txt_file)

    for i, scores in enumerate(words):

        feat = compute_word_features(scores)

        feat["speaker_id"] = speaker
        feat["word_id"] = i+1

        word_rows.append(feat)

machine_word_df = pd.DataFrame(word_rows)

print(machine_word_df.shape)

machine_word_df.head()

from tqdm.notebook import tqdm

from scipy.stats import skew, kurtosis
import numpy as np

def compute_sentence_features(group):

    x = group["mean_gop"].values
    sorted_x = np.sort(x)

    q10 = np.percentile(x,10)
    q25 = np.percentile(x,25)
    q75 = np.percentile(x,75)
    q90 = np.percentile(x,90)

    return {

        # ---------- Central Tendency ----------
        "mean_word_score": np.mean(x),
        "median_word_score": np.median(x),
        "trimmed_mean_word": np.mean(sorted_x[1:-1]) if len(x)>2 else np.mean(x),

        # ---------- Extremes ----------
        "min_word_score": np.min(x),
        "max_word_score": np.max(x),

        "bottom1_word": sorted_x[0],
        "bottom2_word_avg": np.mean(sorted_x[:min(2,len(x))]),
        "bottom3_word_avg": np.mean(sorted_x[:min(3,len(x))]),
        "bottom_half_word_avg": np.mean(sorted_x[:max(1,len(x)//2)]),

        "top1_word": sorted_x[-1],
        "top2_word_avg": np.mean(sorted_x[-min(2,len(x)):]),
        "top3_word_avg": np.mean(sorted_x[-min(3,len(x)):]),

        # ---------- Spread ----------
        "std_word_score": np.std(x),
        "variance_word_score": np.var(x),
        "range_word_score": np.ptp(x),

        "iqr_word": q75-q25,
        "mad_word": np.mean(np.abs(x-np.mean(x))),
        "coeff_var_word": np.std(x)/(np.mean(x)+1e-6),

        # ---------- Percentiles ----------
        "p10_word": q10,
        "p25_word": q25,
        "p75_word": q75,
        "p90_word": q90,

        # ---------- Counts ----------
        "number_of_words": len(x),

        "below2_words": np.sum(x<2),
        "below4_words": np.sum(x<4),
        "below6_words": np.sum(x<6),
        "below8_words": np.sum(x<8),

        "good_words_ratio": np.mean(x>6),
        "excellent_words_ratio": np.mean(x>8),
        "poor_words_ratio": np.mean(x<4),
        "negative_word_ratio": np.mean(x<0),

        # ---------- Length ----------
        "mean_word_length": group["phoneme_count"].mean(),
        "total_phonemes": group["phoneme_count"].sum(),

        # ---------- Shape ----------
        "skew_word": skew(x) if len(x)>2 else 0,
        "kurtosis_word": kurtosis(x) if len(x)>3 else 0,

        # ---------- Consistency ----------
        "top_bottom_gap": np.mean(sorted_x[-min(2,len(x)):]) -
                          np.mean(sorted_x[:min(2,len(x))])
    }
# Ensure sentence_rows is empty before populating with machine data
sentence_rows = []

for speaker, grp in tqdm(machine_word_df.groupby("speaker_id")):

    feat = compute_sentence_features(grp)

    feat["speaker_id"] = speaker

    sentence_rows.append(feat)

machine_sentence_df = pd.DataFrame(sentence_rows)

print(machine_sentence_df.shape)

machine_sentence_df.head()

#Save CSV Files
machine_word_df.to_csv("machine_word_features.csv",index=False)

machine_sentence_df.to_csv("machine_sentence_features.csv",index=False)

print("Saved successfully!")

"""HUMAN GROUND TRUTH"""

import json
import numpy as np
import pandas as pd

import matplotlib.pyplot as plt
import seaborn as sns

from scipy.stats import pearsonr
from scipy.stats import spearmanr

from collections import Counter

plt.style.use("ggplot")
pd.set_option("display.max_columns",None)

import json

json_path = "/content/scores.json"

data = {}

try:
    with open(json_path, "r") as f:
        data = json.load(f)
except json.JSONDecodeError as e:
    print(f"JSONDecodeError: {e}. Attempting a faster recovery from potential file corruption or truncation...")
    with open(json_path, "r", encoding='utf-8', errors='ignore') as f:
        content = f.read()

    # Faster heuristic: Try to find the last valid closing bracket '}' or ']' (assuming the file is a JSON object or array)
    # and parse up to that point. This assumes the primary corruption/truncation is at the end of the file.
    recovered = False
    for i in range(len(content) - 1, -1, -1):
        if content[i] in ['}', ']']:
            try:
                # Attempt to parse the content up to and including this potential closing bracket
                truncated_content = content[:i+1]
                # Ensure the truncated content is not empty before parsing
                if not truncated_content.strip():
                    continue
                data = json.loads(truncated_content)
                print(f"Successfully recovered JSON by truncating at the last valid '{content[i]}' found at index {i}. Data loss may have occurred.")
                recovered = True
                break
            except json.JSONDecodeError:
                # If this substring is still invalid JSON, keep searching backwards
                continue

    if not recovered:
        print("Failed to recover JSON with faster heuristic. The file might be severely corrupted or malformed beyond simple truncation.")
        # If no data could be parsed even with this faster method, re-raise the original error.
        raise e

print("Total Utterances :", len(data))

phoneme_rows = []

word_rows = []

sentence_rows = []

#Parse entire dataset
for utt_id,info in data.items():

    sentence_score = info["total"]

    if isinstance(sentence_score,list):
        sentence_score = np.mean(sentence_score)

    words = info["words"]

    sentence_word_scores = []

    total_phone_scores = []

    content_scores = []
    function_scores = []

    function_words = {
        "the","a","an","is","am","are","was","were",
        "to","of","for","in","on","at","by","with",
        "it","this","that","these","those","we","you",
        "he","she","they","i","our","your","my"
    }

    for word_idx,word in enumerate(words):

        phones = word["phones"]

        phone_scores = word["phones-accuracy"]

        word_score = word["total"]

        if isinstance(word_score,list):
            word_score = np.mean(word_score)

        sentence_word_scores.append(word_score)

        total_phone_scores.extend(phone_scores)

        word_text = word["text"].lower()

        if word_text in function_words:
            function_scores.append(word_score)
        else:
            content_scores.append(word_score)

        # ---------------- PHONEME LEVEL ----------------
        for pid, (phone, score) in enumerate(zip(phones, phone_scores)):

            phoneme_rows.append({
                "utt_id": utt_id,
                "word_id": word_idx + 1,
                "phoneme_id": pid,
                "word": word_text,
                "phoneme": phone,
                "phone_score": score,
                "word_score": word_score,
                "sentence_score": sentence_score
            })


        # ---------------- WORD LEVEL ----------------

        word_rows.append({

            "utt_id": utt_id,

            "word_id": word_idx + 1,

            "word": word_text,

            "num_phonemes": len(phone_scores),

            "mean_phone_score": np.mean(phone_scores),

            "median_phone_score": np.median(phone_scores),

            "min_phone_score": np.min(phone_scores),

            "max_phone_score": np.max(phone_scores),

            "std_phone_score": np.std(phone_scores),

            "range_phone_score": np.max(phone_scores)-np.min(phone_scores),

            "bottom2_mean": np.mean(sorted(phone_scores)[:min(2,len(phone_scores))]),

            "top2_mean": np.mean(sorted(phone_scores)[-min(2,len(phone_scores)):]),

            "num_phone_below8": np.sum(np.array(phone_scores)<8),

            "num_phone_below6": np.sum(np.array(phone_scores)<6),

            "num_phone_below4": np.sum(np.array(phone_scores)<4),

            "word_score": word_score,

            "sentence_score": sentence_score,

            "is_function_word": word_text in function_words

        })

    # ---------------- SENTENCE LEVEL ----------------

    sentence_rows.append({

        "utt_id": utt_id,

        "num_words": len(sentence_word_scores),

        "mean_word_score": np.mean(sentence_word_scores),

        "median_word_score": np.median(sentence_word_scores),

        "min_word_score": np.min(sentence_word_scores),

        "max_word_score": np.max(sentence_word_scores),

        "std_word_score": np.std(sentence_word_scores),

        "range_word_score": np.max(sentence_word_scores)-np.min(sentence_word_scores),

        "num_words_below8": np.sum(np.array(sentence_word_scores)<8),

        "num_words_below6": np.sum(np.array(sentence_word_scores)<6),

        "content_word_average":
            np.mean(content_scores) if len(content_scores)>0 else np.nan,

        "function_word_average":
            np.mean(function_scores) if len(function_scores)>0 else np.nan,

        "sentence_score": sentence_score

    })

phoneme_df = pd.DataFrame(phoneme_rows)
word_df = pd.DataFrame(word_rows)
sentence_df = pd.DataFrame(sentence_rows)

human_word_df = word_df.copy()
human_sentence_df = sentence_df.copy()

# Ensure 'utt_id' is string type, strip any whitespace, and remove leading zeros for consistency
human_word_df['utt_id'] = human_word_df['utt_id'].astype(str).str.strip().str.lstrip('0')
human_sentence_df['utt_id'] = human_sentence_df['utt_id'].astype(str).str.strip().str.lstrip('0')

print("Phoneme Level :", phoneme_df.shape)
print("Word Level    :", human_word_df.shape)
print("Sentence Level:", human_sentence_df.shape)
print("human_word_df columns after processing:", human_word_df.columns.tolist())

#Save CSVs
phoneme_df.to_csv("phoneme_level.csv",index=False)
word_df.to_csv("word_level.csv",index=False)
sentence_df.to_csv("sentence_level.csv",index=False)

print("Saved Successfully")

#PHONEME STATISTICS
phoneme_stats = phoneme_df.groupby("phoneme").agg(

    Frequency=("phone_score","count"),
    Mean=("phone_score","mean"),
    Median=("phone_score","median"),
    Std=("phone_score","std"),
    Minimum=("phone_score","min"),
    Maximum=("phone_score","max")

).sort_values("Mean")
display(phoneme_stats)
phoneme_stats.to_csv("phoneme_statistics.csv")

#HARDEST PHONEMES
print("Lowest Average Scoring Phonemes")
display(phoneme_stats.head(20))

#EASIEST PHONEMES
print("Highest Average Scoring Phonemes")
display(phoneme_stats.tail(20))

import pandas as pd
from scipy.stats import pearsonr, spearmanr

#WORD LENGTH ANALYSIS
word_length = word_df.groupby("num_phonemes").agg(

Average_WordScore=("word_score","mean"),
Count=("word_score","count")

)

display(word_length)
#CONTENT VS FUNCTION WORDS
word_df.groupby("is_function_word")["word_score"].describe()

machine_word_df = word_df.copy()
machine_sentence_df = sentence_df.copy()
machine_word_df = pd.read_csv("machine_word_features.csv")
machine_sentence_df = pd.read_csv("machine_sentence_features.csv")

# Rename 'speaker_id' to 'utt_id' in machine dataframes for merging
machine_word_df = machine_word_df.rename(columns={'speaker_id': 'utt_id'})
machine_sentence_df = machine_sentence_df.rename(columns={'speaker_id': 'utt_id'})

# Convert 'utt_id' to string type and strip any whitespace to ensure consistent types and values for merging
machine_word_df['utt_id'] = machine_word_df['utt_id'].astype(str).str.strip()
machine_sentence_df['utt_id'] = machine_sentence_df['utt_id'].astype(str).str.strip()

print("machine_word_df columns after processing:", machine_word_df.columns.tolist())

#Merge Human and Machine Word Data
word_compare = pd.merge(

    machine_word_df,

    human_word_df[["utt_id","word_id","word_score"]],

    on=["utt_id","word_id"],

    how="inner"

)

print(word_compare.shape)

word_compare.head()

#Merge Human and Machine Word Data
print("Columns in human_word_df before merge:", human_word_df.columns.tolist())
print("Columns in machine_word_df before merge:", machine_word_df.columns.tolist())

# Debugging: check dtypes
print("human_word_df dtypes for merge keys:", human_word_df[['utt_id', 'word_id']].dtypes)
print("machine_word_df dtypes for merge keys:", machine_word_df[['utt_id', 'word_id']].dtypes)

# Debugging: check unique (utt_id, word_id) pairs and their counts
human_keys = set(tuple(x) for x in human_word_df[['utt_id', 'word_id']].values)
machine_keys = set(tuple(x) for x in machine_word_df[['utt_id', 'word_id']].values)

print(f"Number of unique (utt_id, word_id) pairs in human_word_df: {len(human_keys)}")
print(f"Number of unique (utt_id, word_id) pairs in machine_word_df: {len(machine_keys)}")
print(f"Number of common (utt_id, word_id) pairs: {len(human_keys.intersection(machine_keys))}")

# Further Debugging: Print sample utt_ids to identify format discrepancies
print("Sample human_word_df utt_ids:", human_word_df['utt_id'].unique()[:5].tolist())
print("Sample machine_word_df utt_ids:", machine_word_df['utt_id'].unique()[:5].tolist())

word_compare = pd.merge(

    machine_word_df,

    human_word_df[["utt_id","word_id","word_score"]],

    on=["utt_id","word_id"],

    how="inner"

)

print(word_compare.shape)

word_compare.head()

#Merge Human and Machine Sentence Data
sentence_compare = pd.merge(

    machine_sentence_df,

    human_sentence_df[["utt_id","sentence_score"]],

    on="utt_id",

    how="inner"

)

print(sentence_compare.shape)

sentence_compare.head()

"""CORRELATION"""

#Word Feature Correlation
from scipy.stats import pearsonr,spearmanr

results=[]

target="word_score"

ignore=[

    "utt_id",

    "word_id",

    "word",

    "sentence_score",

    "is_function_word"

]

for col in machine_word_df.columns:

    if col in ignore:
        continue

    r,_=pearsonr(

        word_compare[col],

        word_compare[target]

    )

    s,_=spearmanr(

        word_compare[col],

        word_compare[target]

    )

    results.append({

        "Feature":col,

        "Pearson":r,

        "Spearman":s

    })

word_corr=pd.DataFrame(results)

word_corr=word_corr.sort_values(

    "Pearson",

    ascending=False

)

display(word_corr)

#Sentence Feature Correlation
results=[]

target="sentence_score"

ignore=[

    "utt_id"

]

for col in machine_sentence_df.columns:

    if col in ignore:
        continue

    r,_=pearsonr(

        sentence_compare[col],

        sentence_compare[target]

    )

    s,_=spearmanr(

        sentence_compare[col],

        sentence_compare[target]

    )

    results.append({

        "Feature":col,

        "Pearson":r,

        "Spearman":s

    })

sentence_corr=pd.DataFrame(results)

sentence_corr=sentence_corr.sort_values(

    "Pearson",

    ascending=False

)

display(sentence_corr)